### ISSUE TITLE
Can't enable this Plugin due to Error

### ISSUE THREAD

**Issue by xDolphy** [tarngaina/lol_maya#5]
I tried to install several versions of this plugin on both maya 2023 and 2024 and i always get the error:

// Warning: file: C:/Program Files/Autodesk/MayaCreative2023/scripts/others/pluginWin.mel line 316: Plug-in C:/Users/****/Documents/maya/2023Creative/plug-ins/lol_maya.py does not have a valid Autodesk plug-in signature and is not authorized for use with this application

I looked online for solutions to this already but either didnt understand them or tried them and they didnt work.
I dont know much about how programs like maya work internally so help would be greatly apreciated, thanks in advance.

**Comment by MelancholySlime** [comment]
2023Creative ? Try the Maya 2023 Standard version

**Comment by xDolphy** [comment]
> 2023Creative ? Try the Maya 2023 Standard version

Didnt know there is a version besides Creative.
This fixed it though thank you so much ^^
